device: 'cuda'
dataroot: './dataset/dogfacenet'
latent_size: 256
target_resolution: 128
epochs: 10 # for each resolution
checkpoint_frequency: 10

lr: 0.001
b1: 0
b2: 0.99
eps: 0.00000001

batch_size_dict:
  # resolution : batch_size
  4: 16
  8: 16
  16: 16
  32: 16
  64: 16
  128: 16

channel_dict: 
  # resolution : n_channels
  4: 256
  8: 256
  16: 256
  32: 128
  64: 64
  128: 32