device: 'cuda'
dataroot: './dataset/temp/'
latent_size: 512
target_resolution: 512
epochs: 5 # for each phase
flag_tanh: false

delta_p: 0.0001

lr: 0.001
b1: 0
b2: 0.99
eps: 0.00000001

batch_size_dict:
  # resolution : batch_size
  4: 16
  8: 16
  16: 16
  32: 16
  64: 16
  128: 16
  256: 14
  512: 6

channel_dict: 
  # resolution : n_channels
  4: 512
  8: 512
  16: 512
  32: 512
  64: 256
  128: 128
  256: 64
  512: 32